name: Master Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Wait for cheks to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-tests
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: test
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Verify successful tests
        if: steps.wait-for-tests.outputs.conclusion != 'success'
        run: exit 1

  build-linux:
    name: Build Linux
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload Linux Builds
        uses: actions/upload-artifact@v1
        with:
          name: linux-builds
          path: ./target/release/mediaproxy-server

  docker:
    name: Docker
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setting ENV's
        run: echo ::set-env name=VERSION::$(cut -d "#" -f2 <<< $(cargo pkgid))
        shell: bash

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          VERSION: ${{ env.VERSION }}
        with:
          name: thepiconerd/mediaproxy-server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,v${{ env.VERSION }}"

  upload:
    name: Upload
    needs:
      - build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Download Linux Builds
        uses: actions/download-artifact@v1
        with:
          name: linux-builds
          path: ./linux

      - name: Setting ENV's
        run: echo ::set-env name=VERSION::$(cut -d "#" -f2 <<< $(cargo pkgid))
        shell: bash

      - name: Upload Linux Release
        id: upload-linux-asset
        uses: softprops/action-gh-release@v1
        env:
          VERSION: ${{ env.VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            linux/mediaproxy-server
